config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'acme/registrations', sessions: 'acme/sessions' }

  resources :recommendations

  root to: 'projects#index'
  resources :projects do
    resources :comments
  end

  post 'verifications' => 'verifications#create'
  put 'verifications' => 'verifications#verify'
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @recommendations = Recommendation.all
  end

  def show
    @recommendation = Recommendation.find(params[:id])
  end

  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = Recommendation.new(recommendation_params)
    if @recommendation.save
      flash[:notice] = 'Recommendation created successfully!'
      redirect_to recommendations_path
    else
      render :new
    end
  end

  def edit
    @recommendation = Recommendation.find(params[:id])
    render :edit
  end

  def update
    @recommendation = Recommendation.find(params[:id])
    if @recommendation.update(recommendation_params)
      flash[:notice] = 'Recommendation updated successfully!'
      redirect_to recommendations_path(@recommendation)
    else
      render :edit
    end
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy
    flash[:notice] = 'Recommendation destroyed successfully!'
    redirect_to recommendations_path
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:name, :job_description, :email, :phone, :url, :picture)
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.erb
<%= render "layouts/errors", :object => @recommendation %>

<%= form_for @recommendation do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :job_description %><br>
  <%= f.text_field :job_description %><br>
  <%= f.label :email %><br>
  <%= f.email_field :email %><br>
  <%= f.label :phone %><br>
  <%= f.text_field :phone %><br>
  <%= f.label :url %><br>
  <%= f.text_field :url %><br>
  <%= f.file_field :picture %>
  <br>
  <%= f.submit 'Update Recommendation', class: 'btn btn-success' %>
<% end %>

app/views/recommendations/edit.html.erb
<div class="recommendation_index">
<h1>Edit Reccommendation</h1>

<%= render "form" %>
</div>

app/views/recommendations/index.html.erb
<div class="container">
  <div class="recommendation_index">


	<h1>Recomendations</h1>
	<% if @recommendations.any? %>
	<ol>
		<% @recommendations.each do |recommendation| %>
		<li><%= link_to recommendation.name, recommendation_path(recommendation) %></li><br>
    
		<% end %>
	</ol>
	<% else %>
	<p>0 Recommendations</P>
	<% end %>
  </div>
</div>

app/views/recommendations/new.html.erb
<div class="center-align container form-container">
  <h1>New Recommendation</h1>
  <% if @recommendation.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @recommendation.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <%= form_for @recommendation do |f| %>
  <%= f.file_field :picture %><br>
  <%= f.label :name %><br>
  <%= f.text_field :name, class:"form-control" %><br>
  <%= f.label :job_description %><br>
  <%= f.text_field :job_description, class:"form-control" %><br>
  <%= f.label :email %><br>
  <%= f.email_field :email, class:"form-control" %><br>
  <%= f.label :phone %><br>
  <%= f.text_field :phone, class:"form-control" %><br>
  <%= f.label :url %><br>
  <%= f.text_field :url, class:"form-control" %><br>

  <br>
  <%= f.submit "Submit", class:"btn btn-success" %>
  <% end %>
</div>

app/views/recommendations/show.html.erb
<div class="recommendation_index">

<%= image_tag @recommendation.picture_url.to_s, class: 'project_image'%>
<h1>Name:
  <%= @recommendation.name %></h1>
<h3>Job Description:
  <%= @recommendation.job_description %></h3>
<h3>Email:
  <%= link_to @recommendation.email %></h3>
<h3>Phone:
  <%= @recommendation.phone %></h3>
<h3>Url:
  <%= link_to @recommendation.url %></h3>



<%if user_signed_in?%>
<% if current_user.admin? %>
<p><%=link_to "New", new_recommendation_path(@recommendation), class: 'btn btn-info' %>
<%= link_to "Edit", edit_recommendation_path(@recommendation), class: 'btn btn-success' %>
<%= link_to "Delete", @recommendation,
                            :data => {:confirm => "Are you sure?",
                                      :method => "delete"}, class: 'btn btn-danger' %>
<%end%>
<%end%>

<%= link_to "Return to recommendations", recommendations_path, class: 'btn btn-primary' %></p>
</div>