config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'acme/registrations', sessions: 'acme/sessions' }

  resources :recommendations

  root to: 'projects#index'
  resources :projects do
    resources :comments
  end

  post 'verifications' => 'verifications#create'
  put 'verifications' => 'verifications#verify'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :comments, dependent: :delete_all
  validates :title, presence: true
  mount_uploader :picture, PictureUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order('created_at DESC').paginate(per_page: 3, page: params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project added successfully!'
      respond_to do |format|
        format.html { redirect_to projects_path(@project) }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    render :edit
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = 'Project updated successfully!'
      redirect_to projects_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = 'Project destroyed successfully!'
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :link, :description, :skill, :picture)
  end
end

app/views/projects/_form.html.erb
<%= render "layouts/errors", :object => @project %>

<%= form_for @project, remote: true do |f| %>

<%= f.label :link %>
<%= f.text_field :link %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :skill %>
<%= f.text_field :skill %>

<%= f.file_field :picture %>
<br>
<%= f.submit %>
<% end %>

app/views/projects/_project.html.erb
<%= form_for project, remote: true do |f| %>
<%= f.label :old_projects, project.title %>
<%= link_to "(remove)", project, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/projects/_projects.html.erb
<% @projects.each do |project| %>
<div class="col-md-4">
<br>Visit: <%= link_to project.title, project_path(project) %><br>
<%= link_to image_tag project.picture_url.to_s, class: 'project_icon'%><br>
<%= project.created_at.strftime('%A, %B %d') %><br>
</div>
<% end %>
<%= will_paginate @projects, previous_label: "<", next_label: ">" %>

app/views/projects/create.js.erb
$('#new_project').remove();
$('#new_link').show();
$('#old_projects').prepend('<%= j render (@project)%>');

app/views/projects/destroy.js.erb
$('#edit_project_<%= @project.id %>').remove();

app/views/projects/edit.html.erb
<div class="recommendation_index">

  <h1>Edit project</h1>

  <%= render "form" %>
</div>

app/views/projects/index.html.erb
<div class="front_img">
  <div class="about_div">
    <br>
    <div class="img_thumb">
      <%= image_tag "portfolio.png", class: "paul-img img-circle img-responsive"%>
    </div>
    <div class="bio">
      <h1>Who Am I?</h1>
      <p class="text-justify">My name is Paul Nderitu. I am an entrepreneur, and a professional Software Engineer. I am a dreamer, and I believe that technology is the future. If you want to flourish beyond your wildest dreams, I suggest you ask
        me about technology for your idea or business.
        <a href="https://paulnderitu.github.io/portfolio/" class="header-link">Click Here</a>
        For more Repos.</p>
      <br>
      <div class="down-arrow padding-top-15">
        <a href="#about" class="smoothScroll">
          <img src="https://www.servicewiz.com/swizz/resources/css/images/arrow1.png" class="animated infinite fadeInDown"></a>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="container">
    <div class="row tools center-align" id="about">
      <br>
      <h2>Tools I love</h2>
      <hr>
      <div>
        <a href="http://atom.io/"><%= image_tag "atomicon.jpg", class: "soft"%></a>
        <a href="https://github.com/"><%= image_tag "githubicon.png", class: "soft"%></a>
        <a href="https://git-scm.com/"><%= image_tag "giticon.png", class: "soft"%></a>
        <a href="https://jsfiddle.net/"><%= image_tag "jsfiddleicon.png", class: "soft"%></a>
        <a href="https://www.android.com/"><%= image_tag "androidicon.png", class: "soft"%></a>
        <a href="http://fontawesome.io/"><%= image_tag "fontawesomeicon.png", class: "soft"%></a>
      </div>
    </div>
    <!--end of row-->
    <hr>
    <br>
    <div class="row skills">
    <div class="row_skills">
      <div class="tools center-align">
        <h2>Proficient Skills in</h2>
        <hr>
        <a href="https://www.w3schools.com/html/html5_intro.asp"><%= image_tag "htmlicon.jpg", class: "soft"%></a>
        <a href="https://www.w3schools.com/css/css3_intro.asp"><%= image_tag "cssicon.png", class: "soft"%></a>
        <a href="https://www.w3schools.com/js/"><%= image_tag "javascripticon.jpg", class: "soft"%></a>
        <a href="https://jquery.com/"><%= image_tag "jqueryicon.png", class: "soft"%></a>
        <a href="https://www.ruby-lang.org/en/"><%= image_tag "rubyonrailsicon.jpg", class: "soft"%></a>
        <a href="https://www.ruby-lang.org/en/"><%= image_tag "railsicon.png", class: "soft"%></a>
      </div>
      <!--end of tools-->
    </div>
    <!--end of row-->
    <hr>
  </div>
</div>
<div class="webapps container center-align">
  <div class="webap">
    <h2>Web Applications</h2>
    <p>Kindly
      <a href="sign up"><%=link_to "sign up", new_user_registration_path%></a>
      and review any/all of the applications below. Always glad to hear your ideas or suggestions.</p>
  </div>
</div>
<div class="app">
  <br>
  <div class="row">
    <div class="projects" id="old_projects">
      <%= render 'projects' %>
    </div>
  </div>
  <div class="new_project">
    <% if user_signed_in? %>
    <% if current_user.admin? %>
    <%= link_to "New Project", new_project_path, id: "new_link", remote: true%><br>
    <%= link_to "New Recommendation", new_recommendation_path %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/projects/index.js.erb
$("#old_projects").html('<%= j(render("projects"))%>')

app/views/projects/new.html.erb
<div class="recommendation_index">

  <h1>New project</h1>

  <%= render "form" %>
</div>

app/views/projects/new.js.erb
$('#new_link').hide().after('<%= j render("form")%>');

app/views/projects/show.html.erb
<div class="recommendation_index">
  <h2>Click here:
    <a href="<%= @project.link %>"><%= @project.title%></a>
  </h2>
  <%= image_tag @project.picture_url.to_s, class: 'project_image'%>
  <br>

  <h2>Technologies:<%= @project.skill %></h2>

  <h2>Description:</h2>
  <%= @project.description%>

  <br>
  <% if @project.comments.any? %>
  <h2>Here are the reviews for this project:</h2>
  <div class="reviews_show">

    <ol>
      <% @project.comments.each do |comment| %>

      <li><%= comment.user_id %>
        <%= comment.review %></li>
      <% if current_user && current_user.id == comment.user_id %>|
      <%= link_to "Edit", edit_project_comment_path(@project, comment) %>
      |
      <%= link_to "Delete", project_comment_path(@project, comment),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
    </li>
    <% end %>

    <% end %>

  </ol>
</div>
<% if !user_signed_in? %>
<p>Sign in to comment -
  <a href="/users/sign_in">Sign in</a>
</p>
<% end %>

<% else %>
<p>There are no reviews yet!</p>
<% end %>

<% if user_signed_in? %>
<%= link_to "Add a comment", new_project_comment_path(@project) %>
<% if current_user.admin? %>
<p><%= link_to "Edit", edit_project_path(@project) %></p>

<p><%= link_to "Delete", @project,
                          :data => {:confirm => "Are you sure?",
                                    :method => "delete"} %></p>
<% end %>
<% end %>
<p><%= link_to "Return to projects", projects_path %></p>
</div>